### ISSUE TITLE
gRPC

### ISSUE THREAD

**Issue by davidkornel** [cetanu/envoy_data_plane#10]
Hi, I try to use your script to generate gRPC files for envoy by adding extra args lines to the proto args list. The flag I'm using is grpc_python_out, but it seems that the imports are broken. I read that you want to add grpc support in the future for your sovereign project. I thought you might know how to compile the files correctly.

**Comment by cetanu** [comment]
Hello @davidkornel , apologies as I missed this message.

The package published to pypi should contain what you need to set up a grpc server, but you will need to use the stubs and implement methods

I might have a small example on my other computer... I'll paste it here when I get a hold of it

**Comment by cetanu** [comment]
Here's an example where I tried to implement the stubs for CDS:
https://bitbucket.org/atlassian/sovereign/src/563a563603eec0ab5f7aaf0d51404a196520d206/src/sovereign/servicer.py

**Comment by cetanu** [comment]
Let me know if this example is not sufficient! I personally haven't had the time to get a full working example going with an envoy proxy. If I do, I will come back to this thread.
