### ISSUE TITLE
ApiConfigSource of v3 API not generated

### ISSUE THREAD

**Issue by vvoody** [cetanu/envoy_data_plane#11]
Hi @cetanu , thanks for this great library. It does help me a lot.

For some reasons, I'm working on Envoy 1.13.7. After changing version in `download_protobufs.py` to `1.13.7`, Python files were generated successfully.

However, class `ApiConfigSource` in `envoy/config/core/v3/config_source.proto` was not generated.

![image](https://user-images.githubusercontent.com/65963/124436998-2d0d7400-dda9-11eb-89d7-492ab71e7c7e.png)

This `Bootstrap` class is at `src/envoy_data_plane/envoy/config/bootstrap/v3/__init__.py`.

I checked `src/envoy_data_plane/envoy/config/core/v3/__init__.py`, it's not there.

![image](https://user-images.githubusercontent.com/65963/124437372-93929200-dda9-11eb-9883-7f595ee4239d.png)

How could I generate all the specs? Thanks.

**Comment by cetanu** [comment]
Hey there!

Thanks for using this library :) glad it's been good so far.

I just did the same (changed the download script to 1.13.7) and was able to generate the file, and `ApiConfigSource` was in there.

What's your build environment like? I used windows (I can try on other OSes later)
Make sure that the `BUILD` folder in your directory is clean, and that you're using the right dependencies by running commands with `poetry run <cmd>` or `poetry shell`.
If any files are in `BUILD`, the script will skip re-downloading them (I completely removed the `BUILD` folder before running the script just now)

**Comment by vvoody** [comment]
Hi @cetanu , I'm using macOS 10.15.7 and Python 3.8.10.

```
$ python3
Python 3.8.10 (default, May 26 2021, 15:25:55)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

$ git clone https://github.com/cetanu/envoy_data_plane.git
$ cd envoy_data_plane
$ mkdir .venv
$ python3 -m venv .venv/
$ source .venv/bin/activate
$ pip install poetry
$ hash -r
$ which poetry
/Users/me/Downloads/tmp/envoy_data_plane/.venv/bin/poetry
$ poetry install --no-root
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 27 installs, 3 updates, 0 removals
...
$ git diff
diff --git utils/download_protobufs.py utils/download_protobufs.py
index 2ee000f..8f37067 100644
--- utils/download_protobufs.py
+++ utils/download_protobufs.py
@@ -36,9 +36,9 @@ proto_args = [
 Package = namedtuple('Package', ['url', 'name', 'directory'])
 packages = {
     Package(
-        url='https://github.com/envoyproxy/envoy/archive/refs/tags/v1.16.2.zip',
+        url='https://github.com/envoyproxy/envoy/archive/refs/tags/v1.13.7.zip',
         name='envoy',
-        directory='envoy-1.16.2/api'
+        directory='envoy-1.13.7/api'
     ),
     Package(
         url='https://github.com/googleapis/googleapis/archive/master.zip',
(END)

$ rm -rf BUILD
$ ls
LICENSE  README.md  poetry.lock  pyproject.toml  src/  tests/  utils/
$ poetry run python utils/download_protobufs.py
2021-07-06 08:46.31 [info     ] Creating BUILD directory
2021-07-06 08:46.31 [info     ] Downloading opencensus protocol buffers from Github
2021-07-06 08:46.33 [info     ] Extracting opencensus archive
...
```

Build is done. However, no Python class ApiConfigSource generated.
```
$ grep ApiConfigSource src/envoy_data_plane/envoy/config/core/v3/__init__.py
(.venv)
$ echo $?
1
$ grep  ApiConfigSource BUILD/envoy/config/core/v3/config_source.proto
message ApiConfigSource {
  option (udpa.annotations.versioning).previous_message_type = "envoy.api.v2.core.ApiConfigSource";
    ApiConfigSource api_config_source = 2;
```

**Comment by cetanu** [comment]
I did the same on my Macbook, we have the same OSX version and it generated correctly 😕 

I was thinking that I could publish a version to pypi that contains the 1.13.7 protos, but I'm honestly not sure how to package this with python in a way that doesn't interfere with the main package

**Comment by vvoody** [comment]
Thanks @cetanu . Maybe it's a problem of my environment.

**Comment by cetanu** [comment]
I think I might have worked out the problem, I'm just trying to release a new version but I might have to move to github actions instead of travis-ci

**Comment by cetanu** [comment]
I compiled the 1.13.7 protos into a branch, since I don't know if it's possible to separate pypi packages in that way.

You can try installing it with:

```
pip install git+https://github.com/cetanu/envoy_data_plane@envoy_v1.13.7
```

If that works, then you can fork the current master and change the version and it should compile properly now, or you can keep using that branch

**Comment by vvoody** [comment]
Thanks @cetanu, it's very helpful :D

**Comment by cetanu** [comment]
No worries! Let me know if anything else comes up.
